FROM node:22-alpine as dist_builder
WORKDIR /collab-editor
COPY package*.json .
RUN ["npm", "install"]
COPY . .
ARG VITE_SOCKET_SERVER_URL
ENV VITE_SOCKET_SERVER_URL=$VITE_SOCKET_SERVER_URL
RUN ["npm", "run", "build"]

FROM nginx:alpine
COPY --from=dist_builder /collab-editor/dist /usr/share/nginx/html
EXPOSE 80
