name: Deploy to AWS

# 1. The Trigger: When does this run?
on:
  push:
    branches:
      - main

# 2. The Worker: What computer runs this?
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 3. The Action: SSH into AWS and run commands
      - name: Execute SSH commands on AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/MERN_Server/collaborative-editor
            git pull origin main
            cd frontend
            NODE_OPTIONS="--max-old-space-size=1024" npm run build
            cd ..
            pm2 restart all

